### ISSUE TITLE
Pip Install Requirements Fails on M2 Mac, Python 3.9

### ISSUE THREAD

**Issue by EthanJamesLew** [AutoVerse-ai/Verse-library#32]
**Issue**
When running `pip install -r requirements`
I receive the error
```shell
 × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]

      Edit setup.cfg to change the build options; suppress output with --quiet.
...
      BUILDING MATPLOTLIB
        matplotlib: yes [3.4.3]
            python: yes [3.9.18 (main, Sep 11 2023, 08:25:10)  [Clang 14.0.6 ]]
          platform: yes [darwin]
             tests: no  [skipping due to configuration]
            macosx: yes [installing]
Failed to build matplotlib
ERROR: Could not build wheels for matplotlib, which is required to install pyproject.toml-based projects
```

**System Description**
M2 Mac Pro 
Python Python 3.9.18 (Using conda)

**My Fix**
Switch to `z3-solver==4.12.2.0` and `matplotlib==3.8.0`. **The tests pass after doing this.**

**Possible Fixes**
* separate installation instructions for Mac
* unpin / loosen the z3-solver and matplotlib version

**Comment by lyg1597** [comment]
Hi Ethan,

Thank you very much for pointing this out and sorry that this cause problem to you. We will update the dependencies for the tool. Please let us know if you encounter any other problems while using it.

**Comment by rgu01** [comment]
Hi,

The same problem occurred to me and my OS is Ubuntu 22.04.5 LTS, 64 bit. Python is 3.10. The same fix helps me too.

**Comment by lyg1597** [comment]
Thanks for the feedback. I unpin the z3-solver and matplotlib version.
